
CREATE DATABASE datawarehouse_2024_G01;
GO

USE datawarehouse_2024_G01;
GO


DROP TABLE IF EXISTS DIM_CUSTOMER_G01;
CREATE TABLE DIM_CUSTOMER_G01 (
	customerKey INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    customerId INT NOT NULL,
    fullName VARCHAR(255),
    birthDate DATE,
    city VARCHAR(255),
    [state] VARCHAR(255),
    zipcode INT,
	customerCategory CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS DIM_EMPLOYEE_G01 ;
CREATE TABLE DIM_EMPLOYEE_G01 (
	employeeKey INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    employeeId VARCHAR(255) NOT NULL,
    fullName VARCHAR(255) NOT NULL,
    gender CHAR(1) NOT NULL,
    category VARCHAR(255) NOT NULL,
    employmentDate DATE NOT NULL,
    birthDate DATE NOT NULL,
    educationLevel VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS DIM_PRODUCT_G01;
CREATE TABLE DIM_PRODUCT_G01 (
	productKey INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    productId INT NOT NULL,
    detail VARCHAR(255) NOT NULL,
    package VARCHAR(255) NOT NULL,
	liters FLOAT NOT NULL
);

DROP TABLE IF EXISTS DIM_REGIONS_G01;
CREATE TABLE DIM_REGIONS_G01 (
    regionId VARCHAR(255) NOT NULL,
    [state] VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    zipcode INT PRIMARY KEY NOT NULL 
);

DROP TABLE IF EXISTS DIM_PRICES_G01;
CREATE TABLE DIM_PRICES_G01 (
	pricesKey INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    productId int NOT NULL,
    dateFrom date NOT NULL,
    dateUntil date NULL,
    price DECIMAL(5,2) NOT NULL
);

DROP TABLE IF EXISTS DIM_DISCOUNTS_G01;
CREATE TABLE DIM_DISCOUNTS_G01 (
	discountKey INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    discountId int NOT NULL,
    [from] date NOT NULL,
    until date NULL,
	[percentage] INT NOT NULL,
    totalBilling INT NOT NULL,
);

DROP TABLE IF EXISTS DIM_HOLIDAY_G01;
CREATE TABLE DIM_HOLIDAY_G01 (
	datekey INT NOT NULL PRIMARY KEY,
    [date] DATE NOT NULL,
    holiday VARCHAR(255) NOT NULL,
);

--DROP TABLE IF EXISTS FACT_STOCK_G01;
--CREATE TABLE FACT_STOCK_G01 (
--	stockKey INT IDENTITY(1,1) PRIMARY KEY,
--    productId INT NOT NULL,
--    dateKey INT NOT NULL,
--	[date] DATE NOT NULL,
--    variation INT NOT NULL
--);

DROP TABLE IF EXISTS FACT_SALES_G01;
CREATE TABLE FACT_SALES_G01 (
	salesKey INT IDENTITY(1,1) PRIMARY KEY,
    billingId INT NOT NULL, 
    dateKey INT NOT NULL,
    customerKey INT NOT NULL,
	ageRangeCustomer VARCHAR(255),
    employeeKey INT NOT NULL,
    productKey INT NOT NULL,
	[Date] DATE NOT NULL,
    quantity INT NOT NULL,
	region VARCHAR(255) NOT NULL,
	totalAmountSale FLOAT NOT NULL,
	discountAmount FLOAT NULL,
	discountPercentage FLOAT NULL,
	totalLitersSale FLOAT NULL,
	latasVendidas INT NOT NULL
);
DROP TABLE IF EXISTS DIM_TIME_G01;
CREATE TABLE DIM_TIME_G01 (
	Fecha DATE NOT NULL,
	dateKey INT NOT NULL PRIMARY KEY,
    Dia INT NOT NULL,
    Mes INT NOT NULL,
	NombreMes VARCHAR(255) NOT NULL,
	Año INT NOT NULL,
	Trimestre INT NOT NULL,
	Semestre INT NOT NULL,
	DiaSemana INT NOT NULL,
	NombreDiaSemana VARCHAR(255) NOT NULL,
	Semana INT NOT NULL,
	DiaAño INT NOT NULL,
);

ALTER TABLE FACT_SALES_G01 
ADD CONSTRAINT fk_customerKey FOREIGN KEY (customerKey) REFERENCES DIM_CUSTOMER_G01(customerKey);
ALTER TABLE FACT_SALES_G01 
ADD CONSTRAINT fk_employeeKey FOREIGN KEY (employeeKey) REFERENCES DIM_EMPLOYEE_G01(employeeKey);
ALTER TABLE FACT_SALES_G01 
ADD CONSTRAINT fk_productKey FOREIGN KEY (productKey) REFERENCES DIM_PRODUCT_G01(productKey);
ALTER TABLE FACT_SALES_G01 
ADD CONSTRAINT fk_dateKey FOREIGN KEY (dateKey) REFERENCES DIM_TIME_G01(dateKey);
--ALTER TABLE DIM_HOLIDAY_G01
--ADD CONSTRAINT fk_dateKey_dimholiday FOREIGN KEY (dateKey) REFERENCES DIM_TIME_G01(dateKey);
--ALTER TABLE FACT_STOCK_G01 
--ADD CONSTRAINT fk_dateKey_stock FOREIGN KEY (dateKey) REFERENCES DIM_TIME_G01(dateKey);
ALTER TABLE DIM_CUSTOMER_G01 
ADD CONSTRAINT fk_zipcode FOREIGN KEY (zipcode) REFERENCES DIM_REGIONS_G01(zipcode);

--ALTER TABLE FACT_SALES_G01 
--DROP CONSTRAINT fk_customerKey;
--ALTER TABLE FACT_SALES_G01 
--DROP CONSTRAINT fk_employeeKey;
--ALTER TABLE FACT_SALES_G01 
--DROP CONSTRAINT fk_productKey;
--ALTER TABLE FACT_SALES_G01 
--DROP CONSTRAINT fk_dateKey;
--ALTER TABLE DIM_CUSTOMER_G01 
--DROP CONSTRAINT fk_zipcode;

--ALTER TABLE DIM_HOLIDAY_G01
--DROP CONSTRAINT fk_dateKey_dimholiday;
--ALTER TABLE FACT_STOCK_G01 
--DROP CONSTRAINT fk_dateKey_stock;

