CREATE DATABASE bd_staging_2024_G01;
GO
----------------------------------------------Scripts de tablas para el ambiente STG------------------------------------------------

USE bd_staging_2024_G01;
GO
DROP TABLE STG_EMPLOYEE_G01;
CREATE TABLE STG_EMPLOYEE_G01 (
    employeeId VARCHAR(255) NULL,
    fullName VARCHAR(255) NULL,
    gender CHAR(1) NULL,
    category VARCHAR(255) NULL,
    employementDate VARCHAR(255) NULL,
    birthDate VARCHAR(255) NULL,
    educationLevel VARCHAR(255) NULL
);
DROP TABLE STG_HOLIDAYS_G01;
CREATE TABLE STG_HOLIDAYS_G01 (
    DATE VARCHAR(255) NULL,
    holiday VARCHAR(255) NULL
);
DROP TABLE STG_CUSTOMER_G01;
CREATE TABLE STG_CUSTOMER_G01 (
    customerId VARCHAR(255) NULL,
    fullName VARCHAR(255) NULL,
    birthDate VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    STATE VARCHAR(255) NULL,
    zipcode VARCHAR(255) NULL
);
DROP TABLE STG_BILLING_OLD_G01;
CREATE TABLE STG_BILLING_OLD_G01 (
    billingId VARCHAR(255) NULL,
    DATE VARCHAR(255) NULL,
    customerId VARCHAR(255) NULL,
    employeeId VARCHAR(255) NULL,
    productId VARCHAR(255) NULL,
    quantity VARCHAR(255) NULL,
    region VARCHAR(255) NULL
);
DROP TABLE STG_BILLING_NEW_G01;
CREATE TABLE STG_BILLING_NEW_G01 (
    billingId VARCHAR(255) NULL,
    [Date] VARCHAR(255) NULL,
    customerId VARCHAR(255) NULL,
    employeeId VARCHAR(255) NULL,
    region VARCHAR(255) NULL,
    branch_Id VARCHAR(255) NULL
);
DROP TABLE STG_BILLINGDETAIL_G01;
CREATE TABLE STG_BILLINGDETAIL_G01 (
    billingId VARCHAR(255) NULL,
    productId VARCHAR(255) NULL,
    quantity VARCHAR(255) NULL
);
DROP TABLE STG_DISCOUNTS_G01;
CREATE TABLE STG_DISCOUNTS_G01 (
    [discount_id] VARCHAR(255) NULL,
    [percentage] VARCHAR(255) NULL,
	[from] VARCHAR(255) NULL,
	[until] VARCHAR(255) NULL,
	[total_billing] VARCHAR(255) NULL,
);
DROP TABLE STG_PRICES_G01;
CREATE TABLE STG_PRICES_G01 (
    [productId] VARCHAR(255) NULL,
    [price] DECIMAL(5,2) NULL,
	[date] VARCHAR(255),
);
DROP TABLE STG_REGIONS_G01;
CREATE TABLE STG_REGIONS_G01 (
    region_id VARCHAR(255) NULL,
    STATE VARCHAR(255) NULL,
    city VARCHAR(255) NULL,
    zipcode VARCHAR(255) NULL
);
DROP TABLE STG_PRODUCTS_G01;
CREATE TABLE STG_PRODUCTS_G01 (
    productId VARCHAR(255) NULL,
    detail VARCHAR(255) NULL,
    package VARCHAR(255) NULL
);
DROP TABLE STG_STOCK_G01;
CREATE TABLE STG_STOCK_G01 (
    productId VARCHAR(255) NULL,
    DATE VARCHAR(255) NULL,
    variation VARCHAR(255) NULL
);

